version: '3.1'
services:
  db:
    env_file: app/.env
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    env_file: app/.env
    image: redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  app:
    build:
      context: .
    env_file: app/.env
    image: vehicle-app
    restart: always
    environment:
      FLASK_ENV: development
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
